<p>
you are at the room in the north (<<game.current_passage_index>>).
</p>

<p>
you can <<go south|forest__south>> or <<stay|forest__north>>,
or
<<scream(<<game.scream_counter+1>>)|{{
  game.scream_counter += 1;
  alert('AAAA');
}}>>.
<<{
  if (game.scream_counter > 0) {
    return 'times you have screamed: <<(game.scream_counter > 2 ?
    '<<game.scream_counter>>. that is a lot of screaming' :
    '<<game.scream_counter>>.')>>';
  } else {
    return '';
  }
  }>>
</p>